### ISSUE TITLE
How to use JS in Pipeline?

### ISSUE THREAD

**Issue by mskogorevrmc** [raffis/mongodb-query-exporter#23]
I want to get data in 1 hour, but JS is not supported by the exporter. If I wrap JS in quotation marks, then it is treated as a string and is not executed. 

Example:
```
 [
        {
            "$match": {
                "end_time": {
                    "$gte": new Date().getTime()/1000 - new Date().getTime()/1000 % 3600 - 1 * 60 * 60,
                    "$lt": new Date().getTime()/1000 - new Date().getTime()/1000 % 3600 - 0 * 60 * 60
                }
            }
        },
....
]
```
Errors:
```
Mar 18 10:05:38 pc prometheus-mongodb-query-exporter[14594]: panic: While parsing config: yaml: line 26: did not find expected key
Mar 18 10:05:38 pc prometheus-mongodb-query-exporter[14594]: goroutine 1 [running]:
Mar 18 10:05:38 pc prometheus-mongodb-query-exporter[14594]: github.com/raffis/mongodb-query-exporter/cmd.initConfig()
Mar 18 10:05:38 pc prometheus-mongodb-query-exporter[14594]: 	/go/src/github.com/raffis/mongodb-query-exporter/cmd/root.go:144 +0x205
Mar 18 10:05:38 pc prometheus-mongodb-query-exporter[14594]: github.com/spf13/cobra.(*Command).preRun(0x147f3a0)
Mar 18 10:05:38 pc prometheus-mongodb-query-exporter[14594]: 	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:872 +0x49
Mar 18 10:05:38 pc prometheus-mongodb-query-exporter[14594]: github.com/spf13/cobra.(*Command).execute(0x147f3a0, 0xc0000aa160, 0x2, 0x2, 0x147f3a0, 0xc0000aa160)
Mar 18 10:05:38 pc prometheus-mongodb-query-exporter[14594]: 	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:808 +0x14f
Mar 18 10:05:38 pc prometheus-mongodb-query-exporter[14594]: github.com/spf13/cobra.(*Command).ExecuteC(0x147f3a0, 0x0, 0xce2960, 0xc00009c058)
Mar 18 10:05:38 pc prometheus-mongodb-query-exporter[14594]: 	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
Mar 18 10:05:38 pc prometheus-mongodb-query-exporter[14594]: github.com/spf13/cobra.(*Command).Execute(...)
Mar 18 10:05:38 pc prometheus-mongodb-query-exporter[14594]: 	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
Mar 18 10:05:38 pc prometheus-mongodb-query-exporter[14594]: github.com/raffis/mongodb-query-exporter/cmd.Execute(...)
Mar 18 10:05:38 pc prometheus-mongodb-query-exporter[14594]: 	/go/src/github.com/raffis/mongodb-query-exporter/cmd/root.go:93
Mar 18 10:05:38 pc prometheus-mongodb-query-exporter[14594]: main.main()
Mar 18 10:05:38 pc prometheus-mongodb-query-exporter[14594]: 	/go/src/github.com/raffis/mongodb-query-exporter/main.go:8 +0x2e
Mar 18 10:05:38 pc systemd[1]: prometheus-mongodb-query-exporter.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Mar 18 10:05:38 pc systemd[1]: prometheus-mongodb-query-exporter.service: Failed with result 'exit-code'.
Mar 18 10:05:38 pc systemd[1]: prometheus-mongodb-query-exporter.service: Scheduled restart job, restart counter is at 1.
Mar 18 10:05:38 pc prometheus-mongodb-query-exporter[14619]: panic: While parsing config: yaml: line 26: did not find expected key
Mar 18 10:05:38 pc prometheus-mongodb-query-exporter[14619]: goroutine 1 [running]:
Mar 18 10:05:38 pc prometheus-mongodb-query-exporter[14619]: github.com/raffis/mongodb-query-exporter/cmd.initConfig()
Mar 18 10:05:38 pc prometheus-mongodb-query-exporter[14619]: 	/go/src/github.com/raffis/mongodb-query-exporter/cmd/root.go:144 +0x205
Mar 18 10:05:38 pc prometheus-mongodb-query-exporter[14619]: github.com/spf13/cobra.(*Command).preRun(0x147f3a0)
Mar 18 10:05:38 pc prometheus-mongodb-query-exporter[14619]: 	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:872 +0x49
Mar 18 10:05:38 pc prometheus-mongodb-query-exporter[14619]: github.com/spf13/cobra.(*Command).execute(0x147f3a0, 0xc00011a160, 0x2, 0x2, 0x147f3a0, 0xc00011a160)
Mar 18 10:05:38 pc prometheus-mongodb-query-exporter[14619]: 	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:808 +0x14f
Mar 18 10:05:38 pc prometheus-mongodb-query-exporter[14619]: github.com/spf13/cobra.(*Command).ExecuteC(0x147f3a0, 0x0, 0xce2960, 0xc00010c058)
Mar 18 10:05:38 pc prometheus-mongodb-query-exporter[14619]: 	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
Mar 18 10:05:38 pc prometheus-mongodb-query-exporter[14619]: github.com/spf13/cobra.(*Command).Execute(...)
Mar 18 10:05:38 pc prometheus-mongodb-query-exporter[14619]: 	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
Mar 18 10:05:38 pc prometheus-mongodb-query-exporter[14619]: github.com/raffis/mongodb-query-exporter/cmd.Execute(...)
Mar 18 10:05:38 pc prometheus-mongodb-query-exporter[14619]: 	/go/src/github.com/raffis/mongodb-query-exporter/cmd/root.go:93
Mar 18 10:05:38 pc prometheus-mongodb-query-exporter[14619]: main.main()
Mar 18 10:05:38 pc prometheus-mongodb-query-exporter[14619]: 	/go/src/github.com/raffis/mongodb-query-exporter/main.go:8 +0x2e
Mar 18 10:05:38 pc systemd[1]: prometheus-mongodb-query-exporter.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Mar 18 10:05:38 pc systemd[1]: prometheus-mongodb-query-exporter.service: Failed with result 'exit-code'.
Mar 18 10:05:39 pc systemd[1]: prometheus-mongodb-query-exporter.service: Scheduled restart job, restart counter is at 2.
Mar 18 10:05:39 pc prometheus-mongodb-query-exporter[14626]: panic: While parsing config: yaml: line 26: did not find expected key
Mar 18 10:05:39 pc prometheus-mongodb-query-exporter[14626]: goroutine 1 [running]:
Mar 18 10:05:39 pc prometheus-mongodb-query-exporter[14626]: github.com/raffis/mongodb-query-exporter/cmd.initConfig()
Mar 18 10:05:39 pc prometheus-mongodb-query-exporter[14626]: 	/go/src/github.com/raffis/mongodb-query-exporter/cmd/root.go:144 +0x205
Mar 18 10:05:39 pc prometheus-mongodb-query-exporter[14626]: github.com/spf13/cobra.(*Command).preRun(0x147f3a0)
Mar 18 10:05:39 pc prometheus-mongodb-query-exporter[14626]: 	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:872 +0x49
Mar 18 10:05:39 pc prometheus-mongodb-query-exporter[14626]: github.com/spf13/cobra.(*Command).execute(0x147f3a0, 0xc00010e160, 0x2, 0x2, 0x147f3a0, 0xc00010e160)
Mar 18 10:05:39 pc prometheus-mongodb-query-exporter[14626]: 	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:808 +0x14f
Mar 18 10:05:39 pc prometheus-mongodb-query-exporter[14626]: github.com/spf13/cobra.(*Command).ExecuteC(0x147f3a0, 0x0, 0xce2960, 0xc000100058)
Mar 18 10:05:39 pc prometheus-mongodb-query-exporter[14626]: 	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
Mar 18 10:05:39 pc prometheus-mongodb-query-exporter[14626]: github.com/spf13/cobra.(*Command).Execute(...)
Mar 18 10:05:39 pc prometheus-mongodb-query-exporter[14626]: 	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
Mar 18 10:05:39 pc prometheus-mongodb-query-exporter[14626]: github.com/raffis/mongodb-query-exporter/cmd.Execute(...)
Mar 18 10:05:39 pc prometheus-mongodb-query-exporter[14626]: 	/go/src/github.com/raffis/mongodb-query-exporter/cmd/root.go:93
Mar 18 10:05:39 pc prometheus-mongodb-query-exporter[14626]: main.main()
Mar 18 10:05:39 pc prometheus-mongodb-query-exporter[14626]: 	/go/src/github.com/raffis/mongodb-query-exporter/main.go:8 +0x2e
Mar 18 10:05:39 pc systemd[1]: prometheus-mongodb-query-exporter.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Mar 18 10:05:39 pc systemd[1]: prometheus-mongodb-query-exporter.service: Failed with result 'exit-code'.
Mar 18 10:05:39 pc systemd[1]: prometheus-mongodb-query-exporter.service: Scheduled restart job, restart counter is at 3.
Mar 18 10:05:39 pc prometheus-mongodb-query-exporter[14633]: panic: While parsing config: yaml: line 26: did not find expected key
Mar 18 10:05:39 pc prometheus-mongodb-query-exporter[14633]: goroutine 1 [running]:
Mar 18 10:05:39 pc prometheus-mongodb-query-exporter[14633]: github.com/raffis/mongodb-query-exporter/cmd.initConfig()
Mar 18 10:05:39 pc prometheus-mongodb-query-exporter[14633]: 	/go/src/github.com/raffis/mongodb-query-exporter/cmd/root.go:144 +0x205
Mar 18 10:05:39 pc prometheus-mongodb-query-exporter[14633]: github.com/spf13/cobra.(*Command).preRun(0x147f3a0)
Mar 18 10:05:39 pc prometheus-mongodb-query-exporter[14633]: 	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:872 +0x49
Mar 18 10:05:39 pc prometheus-mongodb-query-exporter[14633]: github.com/spf13/cobra.(*Command).execute(0x147f3a0, 0xc000030040, 0x2, 0x2, 0x147f3a0, 0xc000030040)
Mar 18 10:05:39 pc prometheus-mongodb-query-exporter[14633]: 	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:808 +0x14f
Mar 18 10:05:39 pc prometheus-mongodb-query-exporter[14633]: github.com/spf13/cobra.(*Command).ExecuteC(0x147f3a0, 0x0, 0xce2960, 0xc00009c058)
Mar 18 10:05:39 pc prometheus-mongodb-query-exporter[14633]: 	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
Mar 18 10:05:39 pc prometheus-mongodb-query-exporter[14633]: github.com/spf13/cobra.(*Command).Execute(...)
Mar 18 10:05:39 pc prometheus-mongodb-query-exporter[14633]: 	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
Mar 18 10:05:39 pc prometheus-mongodb-query-exporter[14633]: github.com/raffis/mongodb-query-exporter/cmd.Execute(...)
Mar 18 10:05:39 pc prometheus-mongodb-query-exporter[14633]: 	/go/src/github.com/raffis/mongodb-query-exporter/cmd/root.go:93
Mar 18 10:05:39 pc prometheus-mongodb-query-exporter[14633]: main.main()
Mar 18 10:05:39 pc prometheus-mongodb-query-exporter[14633]: 	/go/src/github.com/raffis/mongodb-query-exporter/main.go:8 +0x2e
Mar 18 10:05:39 pc systemd[1]: prometheus-mongodb-query-exporter.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Mar 18 10:05:39 pc systemd[1]: prometheus-mongodb-query-exporter.service: Failed with result 'exit-code'.
Mar 18 10:05:39 pc systemd[1]: prometheus-mongodb-query-exporter.service: Scheduled restart job, restart counter is at 4.
Mar 18 10:05:39 pc prometheus-mongodb-query-exporter[14639]: panic: While parsing config: yaml: line 26: did not find expected key
Mar 18 10:05:39 pc prometheus-mongodb-query-exporter[14639]: goroutine 1 [running]:
Mar 18 10:05:39 pc prometheus-mongodb-query-exporter[14639]: github.com/raffis/mongodb-query-exporter/cmd.initConfig()
Mar 18 10:05:39 pc prometheus-mongodb-query-exporter[14639]: 	/go/src/github.com/raffis/mongodb-query-exporter/cmd/root.go:144 +0x205
Mar 18 10:05:39 pc prometheus-mongodb-query-exporter[14639]: github.com/spf13/cobra.(*Command).preRun(0x147f3a0)
Mar 18 10:05:39 pc prometheus-mongodb-query-exporter[14639]: 	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:872 +0x49
Mar 18 10:05:39 pc prometheus-mongodb-query-exporter[14639]: github.com/spf13/cobra.(*Command).execute(0x147f3a0, 0xc000030190, 0x2, 0x2, 0x147f3a0, 0xc000030190)
Mar 18 10:05:39 pc prometheus-mongodb-query-exporter[14639]: 	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:808 +0x14f
Mar 18 10:05:39 pc prometheus-mongodb-query-exporter[14639]: github.com/spf13/cobra.(*Command).ExecuteC(0x147f3a0, 0x0, 0xce2960, 0xc00003e0b8)
Mar 18 10:05:39 pc prometheus-mongodb-query-exporter[14639]: 	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
Mar 18 10:05:39 pc prometheus-mongodb-query-exporter[14639]: github.com/spf13/cobra.(*Command).Execute(...)
Mar 18 10:05:39 pc prometheus-mongodb-query-exporter[14639]: 	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
Mar 18 10:05:39 pc prometheus-mongodb-query-exporter[14639]: github.com/raffis/mongodb-query-exporter/cmd.Execute(...)
Mar 18 10:05:39 pc prometheus-mongodb-query-exporter[14639]: 	/go/src/github.com/raffis/mongodb-query-exporter/cmd/root.go:93
Mar 18 10:05:39 pc prometheus-mongodb-query-exporter[14639]: main.main()
Mar 18 10:05:39 pc prometheus-mongodb-query-exporter[14639]: 	/go/src/github.com/raffis/mongodb-query-exporter/main.go:8 +0x2e
```
Is it possible to somehow escape JS so that it executed or add this function?

Thanks

**Comment by raffis** [comment]
>  Is it possible to somehow escape JS so that it executed or add this function?

You are trying to use function calls in a MongoDB Shell manner which is no possible as its js. Please have a look here for the solution as this was asked before:

https://github.com/raffis/mongodb-query-exporter/issues/12#issuecomment-725721956

**Comment by mskogorevrmc** [comment]
@raffis Thanks, In this case, I will consider upgrading MongoDB to 4.2 or 4.4

**Comment by mskogorevrmc** [comment]
I think this question can be closed

**Comment by xuanyuanaosheng** [comment]
@raffis  I think use the Mongo console function like Date/ISODate is very useful, because we can put it in the config file directly.

Could your please think about this?

db.ContractStatusChange.aggregate([
{$match:{'cDate':{$gt:ISODate("2021-04-22T05:00:00Z"),$lt:ISODate("2021-04-23T05:00:00Z")},
'data.contractStatus':{$in:['SIGNED','ACTIVE','CANCELLED','REJECTED']}}},
{$project:{"data.contractNumber":true,"data.productChannel":true}},
{$group:{_id:{'no':'$data.contractNumber','channel':'$data.productChannel'}}},
{$group:{_id:'$_id.channel',count:{$sum:1}}}
]);
